/* ===========================================================================
   Which recordings exist, and under what name.

   GENERATED BY `scripts/build-samples.mjs`. Edit the spec in
   `samples.config.mjs` and re-run it; edits made here are overwritten.

   Every cue is listed whether or not it has a recording yet. An empty array
   means "no sample on disk", which `lib/sfx.ts` reports as not-ready and every
   caller answers by playing the synthesised cue it already has. That is what
   lets this whole layer land before a single file has been chosen: the site
   sounds exactly as it does today until a cue's array fills in, and then it
   changes one cue at a time.
   =========================================================================== */

/**
 * The cues that are pictures of real objects.
 *
 * Deliberately not every sound on the site. The chime, the copy confirm, the
 * theme click, the waitlist celebration and the room swell are abstractions —
 * nothing in the world makes those noises — and a recording would make them
 * worse, so they are not addressable from here at all.
 */
export type SfxCue =
  /* Scratch card. The rub is a sustaining loop rather than one-shots; see the
     reversal argued in ScratchCard/rasp.ts. */
  | "scratch-rub"
  | "scratch-body"
  | "scratch-peel"
  /* Photographs. `photo-shuffle` is deliberately absent: a category change is
     built at runtime from three to five overlapping `photo-slip` variants plus
     `photo-settle`, so the two events are guaranteed to be the same material
     rather than two separately chosen recordings that drift apart. */
  | "photo-slip"
  | "photo-settle"
  /* Book. The riffles are their own takes rather than many `book-page`s — a
     real thumb release is not a page turn repeated, which is exactly the thing
     the 42-contact scheduler got wrong. */
  | "book-page"
  | "book-riffle-open"
  | "book-riffle-close"
  | "book-boards"
  /* Stickers. */
  | "sticker-rifle"
  | "sticker-rocket"
  | "sticker-kick"
  | "sticker-punch"
  /* The rest of the board. */
  | "key-press"
  | "key-enter"
  | "printer-run"
  | "pencil-draw"
  | "needle-drop"
  | "needle-lift"
  /* The one homepage cue that is a picture of an object. */
  | "jet-pass"
  /* Found's phone: a real motor on real wood, played twice per text by
     lib/found/buzz.ts. */
  | "found-buzz";

export type SfxEntry = {
  /** Filenames under `/sfx/`. More than one is a round-robin — see `pick` in
   *  lib/sfx.ts. Empty means no recording yet. */
  readonly takes: readonly string[];
  /** Per-cue trim, in dB, decided in the bench and measured by
   *  `scripts/measure-sfx.mjs`. Applied on top of the caller's own level. */
  readonly gain: number;
  /** Whether this cue sustains under a gesture rather than firing once. */
  readonly sustained?: boolean;
};

/* @generated:start — scripts/build-samples.mjs rewrites everything below. */
export const SFX: Record<SfxCue, SfxEntry> = {
  "scratch-rub": { takes: ["scratch-rub-1.m4a", "scratch-rub-2.m4a"], gain: 1, sustained: true },
  "scratch-body": { takes: ["scratch-body-1.m4a", "scratch-body-2.m4a"], gain: 1 },
  "scratch-peel": { takes: ["scratch-peel-1.m4a", "scratch-peel-2.m4a"], gain: 1 },
  "photo-slip": { takes: ["photo-slip-1.m4a", "photo-slip-2.m4a", "photo-slip-3.m4a"], gain: 1 },
  "photo-settle": { takes: ["photo-settle-1.m4a", "photo-settle-2.m4a"], gain: 1 },
  "book-page": { takes: ["book-page-1.m4a", "book-page-2.m4a", "book-page-3.m4a"], gain: 1 },
  "book-riffle-open": { takes: ["book-riffle-open-1.m4a", "book-riffle-open-2.m4a"], gain: 1 },
  "book-riffle-close": { takes: ["book-riffle-close-1.m4a", "book-riffle-close-2.m4a"], gain: 1 },
  "book-boards": { takes: ["book-boards-1.m4a", "book-boards-2.m4a"], gain: 1 },
  "sticker-rifle": { takes: ["sticker-rifle-1.m4a", "sticker-rifle-2.m4a"], gain: 1 },
  "sticker-rocket": { takes: ["sticker-rocket-1.m4a", "sticker-rocket-2.m4a"], gain: 1 },
  "sticker-kick": { takes: ["sticker-kick-1.m4a", "sticker-kick-2.m4a"], gain: 1 },
  "sticker-punch": { takes: ["sticker-punch-1.m4a", "sticker-punch-2.m4a"], gain: 1 },
  "key-press": { takes: ["key-press-1.m4a", "key-press-2.m4a", "key-press-3.m4a"], gain: 1 },
  "key-enter": { takes: ["key-enter-1.m4a", "key-enter-2.m4a"], gain: 1 },
  "printer-run": { takes: ["printer-run-1.m4a", "printer-run-2.m4a"], gain: 1 },
  "pencil-draw": { takes: ["pencil-draw-1.m4a", "pencil-draw-2.m4a"], gain: 1, sustained: true },
  "needle-drop": { takes: ["needle-drop-1.m4a", "needle-drop-2.m4a"], gain: 1 },
  "needle-lift": { takes: ["needle-lift-1.m4a", "needle-lift-2.m4a"], gain: 1 },
  "jet-pass": { takes: ["jet-pass-1.m4a", "jet-pass-2.m4a"], gain: 1, sustained: true },
  "found-buzz": { takes: ["found-buzz-1.m4a", "found-buzz-2.m4a"], gain: 1 },
};
/* @generated:end */

export const CUES = Object.keys(SFX) as SfxCue[];
